version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=2170171
      - MYSQL_DATABASE=algoritmosp
    volumes:
      - ./data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
